module.exports = {
    SERVER_URL: "http://localhost:3000",
    // SERVER_URL: "https://hacademy-api.herokuapp.com",
    GET_START: "GET_START",
    MENU: {
        WEBSITE: "MENU_WEBSITE",
        HELP: "MENU_HELP",
        FEATURES: "MENU_FEATURE"
    },
    FEATURE: {
        LOGIN: "FEATURE_LOGIN",
        LOGOUT: "FEATURE_LOGOUT",
        SURVEY: "FEATURE_SURVEY",
        SCHEDULE: "FEATURE_SCHEDULE"
    },
    COURSE: {
        COURSES: "COURSES",
        POPULAR_COURSES: "POPULAR_COURSES",
        LATEST_COURSES: "LATEST_COURSES",
    },
    SUBJECT: {
        SUBJECTS: "SUBJECTS"
    },
    PROFILE: {
        CHECK_CART: "PROFILE_CHECK_CART",
        ADD_TO_CART: "PROFILE_ADD_TO_CART",
        PAYMENT: "PROFILE_PAYMENT",
        CHANGE_FIRSTNAME: "PROFILE_CHANGE_FIRSTNAME",
        CHANGE_LASTNAME: "PROFILE_CHANGE_LASTNAME",
        CHANGE_IMAGEURL: "PROFILE_CHANGE_IMAGEURL",
        FORGOT_PASSWORD: "PROFILE_FORGOT_PASSWORD",
        CHANGE_PASSWORD: "PROFILE_CHANGE_PASSWORD",
    }
}