module.exports = {
    SECRET_KEY_STRIPE: "sk_test_JFlP6I3IseQdbqWYmAhE93vh00iVqllbei",
    CONNECTION_STRING: "mongodb+srv://dbCafocc:dbcafocc@cafocc-iax21.gcp.mongodb.net/hacademy?retryWrites=true&w=majority",
    JWT_SECRET: process.env.JWT_SECRET || "jwt_secret",
    GOOGLE_CLIENT_ID: "225505233278-fga9fpdso8hld9l6j05ltm6urf22l98n.apps.googleusercontent.com",
    GOOGLE_CLIENT_SECRET: "UFSa4vT7lfDYMRMiutESZNzc",
    FACEBOOK_CLIENT_ID: "1811382482329129",
    FACEBOOK_CLIENT_SECRET: "e78cb8ed7b344d7e71e00bdd6bd8b9b9",
    USERNAME_EMAIL: 'dhtc.kltn@gmail.com',
    PASSWORD_EMAIL: 'HaiTom!1',
    EMAIL_SECRET: "email_secret",
    URL_CLIENT: "http://localhost:3001",
    URL_ADMIN: "http://localhost:3002",
    // URL_CLIENT: "https://cafocc.web.app",
    // URL_ADMIN: "https://cafocc-cms.web.app",
}
